version: "3.3"
services: 
  postgres:
    image: "postgres:latest"
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - postgres-data:/data/postgres
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    
  testdb:
    image: "postgres:latest"
    restart: always
    ports: 
      - "5433:5432"
    volumes: 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_DB}
    networks:
      - app-network

volumes: 
  postgres-data:

networks:
  app-network: