version: '3.1'

services: 
  postgres:
    image: "postgres:latest"
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - postgres-data:/data/postgres
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network

  nginx:
    image: nginx:1.21
    container_name: nginx
    volumes: 
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
    restart: always
    networks:
      - app-network
    depends_on: 
      - fastapi

  fastapi:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks: 
      - app-network
    depends_on: 
      - postgres

volumes: 
  postgres-data:

networks: 
  app-network: